"""add files table

Revision ID: f6c436735538
Revises: aefafece07f0
Create Date: 2025-09-14 00:18:49.754064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c436735538'
down_revision: Union[str, Sequence[str], None] = 'aefafece07f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fileId', sa.String(length=36), nullable=False),
    sa.Column('fileUri', sa.Text(), nullable=False),
    sa.Column('fileThumbnailUri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_fileId'), 'files', ['fileId'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_fileId'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
